version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: local-localstack-my-drive
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/.data
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/.data

volumes:
  localstack_data:
