version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: drive-local-postgres
    environment:
      POSTGRES_DB: drive_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: local-localstack-drive
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/.data
    ports:
      - "4566:4566"
    volumes:
      - localstack_data_drive:/.data

volumes:
  postgres_data:
  localstack_data_drive:
