CREATE TABLE USERS
(
    ID            UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    UID           TEXT              NOT NULL,
    FIRST_NAME    VARCHAR(255)      NOT NULL,
    LAST_NAME     VARCHAR(255)      NOT NULL,
    EMAIL         VARCHAR(255)      NOT NULL,
    STORAGE_USED  BIGINT            DEFAULT 0,
    STORAGE_LIMIT BIGINT            DEFAULT 15000000000,
    CREATED_ON    TIMESTAMP         DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DIRECTORIES
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(255)               NOT NULL,
    IS_STARRED  BOOLEAN   DEFAULT FALSE,
    IS_DELETED  BOOLEAN   DEFAULT FALSE,
    PARENT_DIR  INT REFERENCES DIRECTORIES (ID),
    OWNER_ID    UUID REFERENCES USERS (ID) NOT NULL,
    CREATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FILES
(
    ID                SERIAL PRIMARY KEY,
    NAME              VARCHAR(255)               NOT NULL,
    BLOB_REFERENCE_ID UUID                       NOT NULL,
    IS_STARRED        BOOLEAN   DEFAULT FALSE,
    IS_DELETED        BOOLEAN   DEFAULT FALSE,
    OWNER_ID          UUID REFERENCES USERS (ID) NOT NULL,
    PARENT_DIR        INT REFERENCES DIRECTORIES (ID),
    CREATED_ON        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE FILE_METADATA
(
    ID           SERIAL PRIMARY KEY,
    FILE_ID      INT REFERENCES FILES (ID) ON DELETE CASCADE,
    SIZE         BIGINT       NOT NULL, --BYTES
    MIME_TYPE    VARCHAR(255) NOT NULL,
    EXTENSION    VARCHAR(50),
    WIDTH        INTEGER,
    HEIGHT       INTEGER,
    DURATION     DECIMAL(10, 3),
    ENCODING     VARCHAR(255),
    BITRATE      INTEGER,
    FRAME_RATE   DECIMAL(5, 2),
    THUMBNAIL_ID UUID
);

CREATE TABLE SHARED_ITEMS
(
    ID           SERIAL PRIMARY KEY,
    FILE_ID      INT REFERENCES FILES (ID),
    DIRECTORY_ID INT REFERENCES DIRECTORIES (ID),
    USER_ID      UUID REFERENCES USERS (ID),
    ITEM_TYPE    VARCHAR(20)
);

CREATE TABLE RECENT_ITEMS
(
    ID           SERIAL PRIMARY KEY,
    USER_ID      UUID REFERENCES USERS (ID) NOT NULL,
    FILE_ID      INT REFERENCES FILES (ID),
    DIRECTORY_ID INT REFERENCES DIRECTORIES (ID),
    ACTION_TYPE  VARCHAR(50),
    ITEM_TYPE    VARCHAR(20)
);